// Mega Menu Data Structure
// 10 Industries, each with 20 solutions (5x4 grid)

export type Solution = {
  title: string;
  description: string;
  href: string;
  icon?: string;
};

export type Industry = {
  id: string;
  name: string;
  description: string;
  solutions: Solution[];
};

export const INDUSTRIES: Industry[] = [
  {
    id: "fintech",
    name: "FinTech",
    description: "Financial services & banking platforms",
    solutions: [
      { title: "Payment Gateway", description: "Secure payment processing", href: "/solutions/payment-gateway" },
      { title: "Digital Banking", description: "Core banking systems", href: "/solutions/digital-banking" },
      { title: "Blockchain Wallets", description: "Crypto & digital assets", href: "/solutions/blockchain-wallets" },
      { title: "KYC Automation", description: "Identity verification", href: "/solutions/kyc-automation" },
      { title: "Fraud Detection", description: "AI-powered security", href: "/solutions/fraud-detection" },
      { title: "Lending Platforms", description: "Loan origination systems", href: "/solutions/lending-platforms" },
      { title: "Wealth Management", description: "Investment platforms", href: "/solutions/wealth-management" },
      { title: "Insurance Tech", description: "Policy & claims systems", href: "/solutions/insurance-tech" },
      { title: "Trading Platforms", description: "Real-time trading", href: "/solutions/trading-platforms" },
      { title: "RegTech Compliance", description: "Regulatory reporting", href: "/solutions/regtech-compliance" },
      { title: "P2P Transfers", description: "Peer payments", href: "/solutions/p2p-transfers" },
      { title: "Neobank Core", description: "Digital-first banking", href: "/solutions/neobank-core" },
      { title: "Credit Scoring", description: "Alternative scoring", href: "/solutions/credit-scoring" },
      { title: "Open Banking APIs", description: "Financial data APIs", href: "/solutions/open-banking-apis" },
      { title: "POS Systems", description: "Point of sale", href: "/solutions/pos-systems" },
      { title: "Robo-Advisory", description: "Automated investing", href: "/solutions/robo-advisory" },
      { title: "Bill Payment", description: "Automated billing", href: "/solutions/bill-payment" },
      { title: "FX Trading", description: "Currency exchange", href: "/solutions/fx-trading" },
      { title: "Accounting Automation", description: "Financial reconciliation", href: "/solutions/accounting-automation" },
      { title: "Tax Compliance", description: "Automated tax filing", href: "/solutions/tax-compliance" },
    ],
  },
  {
    id: "healthcare",
    name: "HealthTech",
    description: "Medical & healthcare solutions",
    solutions: [
      { title: "Telemedicine", description: "Virtual consultations", href: "/solutions/telemedicine" },
      { title: "EHR Systems", description: "Electronic health records", href: "/solutions/ehr-systems" },
      { title: "Patient Portal", description: "Self-service access", href: "/solutions/patient-portal" },
      { title: "Medical Imaging", description: "DICOM & PACS", href: "/solutions/medical-imaging" },
      { title: "Lab Management", description: "Results & workflows", href: "/solutions/lab-management" },
      { title: "Pharmacy Systems", description: "Prescription management", href: "/solutions/pharmacy-systems" },
      { title: "Clinical Trials", description: "Research platforms", href: "/solutions/clinical-trials" },
      { title: "Health Analytics", description: "Population health", href: "/solutions/health-analytics" },
      { title: "Remote Monitoring", description: "IoT devices & wearables", href: "/solutions/remote-monitoring" },
      { title: "Appointment Booking", description: "Scheduling systems", href: "/solutions/appointment-booking" },
      { title: "Medical Billing", description: "Claims processing", href: "/solutions/medical-billing" },
      { title: "Drug Discovery", description: "AI-powered research", href: "/solutions/drug-discovery" },
      { title: "Mental Health Apps", description: "Digital therapy", href: "/solutions/mental-health-apps" },
      { title: "Care Coordination", description: "Provider networks", href: "/solutions/care-coordination" },
      { title: "Medical Devices", description: "Device integration", href: "/solutions/medical-devices" },
      { title: "Health Insurance", description: "Claims & benefits", href: "/solutions/health-insurance" },
      { title: "Genomics Platforms", description: "DNA sequencing", href: "/solutions/genomics-platforms" },
      { title: "Nutrition Tracking", description: "Diet & wellness", href: "/solutions/nutrition-tracking" },
      { title: "Hospital Management", description: "Operations systems", href: "/solutions/hospital-management" },
      { title: "Diagnostics AI", description: "Automated diagnosis", href: "/solutions/diagnostics-ai" },
    ],
  },
  {
    id: "ecommerce",
    name: "E-Commerce",
    description: "Retail & marketplace platforms",
    solutions: [
      { title: "Online Storefront", description: "Custom shops", href: "/solutions/online-storefront" },
      { title: "Marketplace Platform", description: "Multi-vendor systems", href: "/solutions/marketplace-platform" },
      { title: "Product Catalog", description: "Inventory management", href: "/solutions/product-catalog" },
      { title: "Shopping Cart", description: "Checkout optimization", href: "/solutions/shopping-cart" },
      { title: "Order Management", description: "Fulfillment systems", href: "/solutions/order-management" },
      { title: "Customer Reviews", description: "Rating & feedback", href: "/solutions/customer-reviews" },
      { title: "Recommendation Engine", description: "Personalization", href: "/solutions/recommendation-engine" },
      { title: "Loyalty Programs", description: "Rewards & points", href: "/solutions/loyalty-programs" },
      { title: "Dynamic Pricing", description: "Smart pricing", href: "/solutions/dynamic-pricing" },
      { title: "AR Try-On", description: "Virtual fitting", href: "/solutions/ar-try-on" },
      { title: "Subscription Box", description: "Recurring commerce", href: "/solutions/subscription-box" },
      { title: "Live Shopping", description: "Video commerce", href: "/solutions/live-shopping" },
      { title: "Social Commerce", description: "Shoppable posts", href: "/solutions/social-commerce" },
      { title: "Warehouse System", description: "Logistics automation", href: "/solutions/warehouse-system" },
      { title: "Returns Portal", description: "RMA management", href: "/solutions/returns-portal" },
      { title: "Gift Registry", description: "Wish lists", href: "/solutions/gift-registry" },
      { title: "B2B Portal", description: "Wholesale systems", href: "/solutions/b2b-portal" },
      { title: "Dropshipping", description: "Supplier integration", href: "/solutions/dropshipping" },
      { title: "POS Integration", description: "Omnichannel retail", href: "/solutions/pos-integration" },
      { title: "Search & Filters", description: "Product discovery", href: "/solutions/search-filters" },
    ],
  },
  {
    id: "edtech",
    name: "EdTech",
    description: "Education & learning platforms",
    solutions: [
      { title: "LMS Platform", description: "Learning management", href: "/solutions/lms-platform" },
      { title: "Virtual Classroom", description: "Live sessions", href: "/solutions/virtual-classroom" },
      { title: "Student Portal", description: "Academic access", href: "/solutions/student-portal" },
      { title: "Course Builder", description: "Content authoring", href: "/solutions/course-builder" },
      { title: "Assessment Tools", description: "Quizzes & exams", href: "/solutions/assessment-tools" },
      { title: "Gradebook", description: "Performance tracking", href: "/solutions/gradebook" },
      { title: "Video Lectures", description: "On-demand learning", href: "/solutions/video-lectures" },
      { title: "Interactive Labs", description: "Hands-on practice", href: "/solutions/interactive-labs" },
      { title: "Study Groups", description: "Peer collaboration", href: "/solutions/study-groups" },
      { title: "Certification", description: "Digital credentials", href: "/solutions/certification" },
      { title: "Tutoring Platform", description: "1-on-1 sessions", href: "/solutions/tutoring-platform" },
      { title: "Language Learning", description: "Adaptive lessons", href: "/solutions/language-learning" },
      { title: "School Admin", description: "SIS systems", href: "/solutions/school-admin" },
      { title: "Parent Portal", description: "Family engagement", href: "/solutions/parent-portal" },
      { title: "Attendance Tracking", description: "Automated records", href: "/solutions/attendance-tracking" },
      { title: "Library System", description: "Digital resources", href: "/solutions/library-system" },
      { title: "Career Services", description: "Job placement", href: "/solutions/career-services" },
      { title: "Alumni Network", description: "Community platform", href: "/solutions/alumni-network" },
      { title: "Admission Portal", description: "Application system", href: "/solutions/admission-portal" },
      { title: "Learning Analytics", description: "Student insights", href: "/solutions/learning-analytics" },
    ],
  },
  {
    id: "logistics",
    name: "Logistics",
    description: "Supply chain & transportation",
    solutions: [
      { title: "Fleet Management", description: "Vehicle tracking", href: "/solutions/fleet-management" },
      { title: "Route Optimization", description: "Smart routing", href: "/solutions/route-optimization" },
      { title: "Warehouse System", description: "Inventory control", href: "/solutions/warehouse-system-logistics" },
      { title: "Last Mile Delivery", description: "Final delivery", href: "/solutions/last-mile-delivery" },
      { title: "Freight Booking", description: "Carrier platform", href: "/solutions/freight-booking" },
      { title: "Customs Clearance", description: "Border automation", href: "/solutions/customs-clearance" },
      { title: "Track & Trace", description: "Shipment visibility", href: "/solutions/track-trace" },
      { title: "Cold Chain", description: "Temperature monitoring", href: "/solutions/cold-chain" },
      { title: "Dock Scheduling", description: "Yard management", href: "/solutions/dock-scheduling" },
      { title: "Returns Logistics", description: "Reverse supply chain", href: "/solutions/returns-logistics" },
      { title: "Driver App", description: "Mobile delivery", href: "/solutions/driver-app" },
      { title: "Load Planning", description: "Capacity optimization", href: "/solutions/load-planning" },
      { title: "Customs Broker", description: "Compliance docs", href: "/solutions/customs-broker" },
      { title: "Cross-Docking", description: "Direct transfer", href: "/solutions/cross-docking" },
      { title: "3PL Platform", description: "Third-party logistics", href: "/solutions/3pl-platform" },
      { title: "Carrier Portal", description: "Partner integration", href: "/solutions/carrier-portal" },
      { title: "Freight Audit", description: "Cost reconciliation", href: "/solutions/freight-audit" },
      { title: "Demand Forecasting", description: "Predictive planning", href: "/solutions/demand-forecasting" },
      { title: "Shipping Labels", description: "Label automation", href: "/solutions/shipping-labels" },
      { title: "Geo-Fencing", description: "Location alerts", href: "/solutions/geo-fencing" },
    ],
  },
  {
    id: "realestate",
    name: "Real Estate",
    description: "Property & construction tech",
    solutions: [
      { title: "Property Listings", description: "MLS integration", href: "/solutions/property-listings" },
      { title: "Virtual Tours", description: "3D walkthroughs", href: "/solutions/virtual-tours" },
      { title: "CRM for Agents", description: "Lead management", href: "/solutions/crm-agents" },
      { title: "Booking System", description: "Viewing scheduler", href: "/solutions/booking-system-realestate" },
      { title: "Property Valuation", description: "AVM tools", href: "/solutions/property-valuation" },
      { title: "Mortgage Portal", description: "Loan applications", href: "/solutions/mortgage-portal" },
      { title: "Lease Management", description: "Tenant systems", href: "/solutions/lease-management" },
      { title: "Maintenance Requests", description: "Work orders", href: "/solutions/maintenance-requests" },
      { title: "HOA Portal", description: "Community management", href: "/solutions/hoa-portal" },
      { title: "Rent Collection", description: "Payment automation", href: "/solutions/rent-collection" },
      { title: "Smart Home IoT", description: "Building automation", href: "/solutions/smart-home-iot" },
      { title: "Construction PM", description: "Project tracking", href: "/solutions/construction-pm" },
      { title: "BIM Platform", description: "3D modeling", href: "/solutions/bim-platform" },
      { title: "Bidding System", description: "Contractor quotes", href: "/solutions/bidding-system" },
      { title: "Site Inspection", description: "Mobile audits", href: "/solutions/site-inspection" },
      { title: "Energy Management", description: "Utility tracking", href: "/solutions/energy-management" },
      { title: "Co-Working Booking", description: "Space reservations", href: "/solutions/coworking-booking" },
      { title: "Property Analytics", description: "Market insights", href: "/solutions/property-analytics" },
      { title: "Document Vault", description: "Secure storage", href: "/solutions/document-vault" },
      { title: "Title Search", description: "Deed verification", href: "/solutions/title-search" },
    ],
  },
  {
    id: "automotive",
    name: "Automotive",
    description: "Connected vehicles & mobility",
    solutions: [
      { title: "Fleet Telematics", description: "Vehicle data", href: "/solutions/fleet-telematics" },
      { title: "Ride Sharing", description: "Mobility platforms", href: "/solutions/ride-sharing" },
      { title: "Car Rental", description: "Booking systems", href: "/solutions/car-rental" },
      { title: "EV Charging", description: "Station network", href: "/solutions/ev-charging" },
      { title: "Auto Insurance", description: "Usage-based pricing", href: "/solutions/auto-insurance" },
      { title: "Parts Marketplace", description: "Aftermarket platform", href: "/solutions/parts-marketplace" },
      { title: "Service Booking", description: "Mechanic scheduler", href: "/solutions/service-booking" },
      { title: "Diagnostic Tools", description: "OBD-II systems", href: "/solutions/diagnostic-tools" },
      { title: "Connected Car", description: "Infotainment APIs", href: "/solutions/connected-car" },
      { title: "Parking Platform", description: "Space finder", href: "/solutions/parking-platform" },
      { title: "Dealer CRM", description: "Sales management", href: "/solutions/dealer-crm" },
      { title: "Test Drive Booking", description: "Showroom tools", href: "/solutions/test-drive-booking" },
      { title: "Trade-In Valuation", description: "Instant quotes", href: "/solutions/trade-in-valuation" },
      { title: "Auto Financing", description: "Loan calculators", href: "/solutions/auto-financing" },
      { title: "Roadside Assistance", description: "Emergency dispatch", href: "/solutions/roadside-assistance" },
      { title: "Vehicle Tracking", description: "GPS monitoring", href: "/solutions/vehicle-tracking" },
      { title: "Carpool Platform", description: "Shared commutes", href: "/solutions/carpool-platform" },
      { title: "Toll Payment", description: "Automated tolls", href: "/solutions/toll-payment" },
      { title: "Driver Safety", description: "Behavior analytics", href: "/solutions/driver-safety" },
      { title: "Auction Platform", description: "Wholesale marketplace", href: "/solutions/auction-platform" },
    ],
  },
  {
    id: "travel",
    name: "Travel & Hospitality",
    description: "Tourism & booking platforms",
    solutions: [
      { title: "Hotel Booking", description: "Reservations system", href: "/solutions/hotel-booking" },
      { title: "Flight Search", description: "GDS integration", href: "/solutions/flight-search" },
      { title: "Tour Packages", description: "Itinerary builder", href: "/solutions/tour-packages" },
      { title: "Activity Booking", description: "Experience platform", href: "/solutions/activity-booking" },
      { title: "Travel CRM", description: "Agent tools", href: "/solutions/travel-crm" },
      { title: "Loyalty Programs", description: "Rewards systems", href: "/solutions/loyalty-programs-travel" },
      { title: "Property Management", description: "Hotel operations", href: "/solutions/property-management" },
      { title: "Channel Manager", description: "OTA distribution", href: "/solutions/channel-manager" },
      { title: "Revenue Management", description: "Dynamic pricing", href: "/solutions/revenue-management" },
      { title: "Guest Portal", description: "Self-service", href: "/solutions/guest-portal" },
      { title: "Concierge App", description: "Guest services", href: "/solutions/concierge-app" },
      { title: "Restaurant POS", description: "F&B systems", href: "/solutions/restaurant-pos" },
      { title: "Event Management", description: "Venue booking", href: "/solutions/event-management" },
      { title: "Travel Insurance", description: "Policy management", href: "/solutions/travel-insurance" },
      { title: "Visa Services", description: "Document processing", href: "/solutions/visa-services" },
      { title: "Currency Exchange", description: "FX platform", href: "/solutions/currency-exchange" },
      { title: "Cruise Booking", description: "Sailing reservations", href: "/solutions/cruise-booking" },
      { title: "Car Hire", description: "Rental integration", href: "/solutions/car-hire" },
      { title: "Travel Guides", description: "Destination info", href: "/solutions/travel-guides" },
      { title: "Group Travel", description: "Corporate bookings", href: "/solutions/group-travel" },
    ],
  },
  {
    id: "media",
    name: "Media & Entertainment",
    description: "Content & streaming platforms",
    solutions: [
      { title: "Video Streaming", description: "OTT platforms", href: "/solutions/video-streaming" },
      { title: "Music Platform", description: "Audio streaming", href: "/solutions/music-platform" },
      { title: "Podcast Hosting", description: "Distribution systems", href: "/solutions/podcast-hosting" },
      { title: "Live Broadcasting", description: "Real-time streaming", href: "/solutions/live-broadcasting" },
      { title: "Content CMS", description: "Media management", href: "/solutions/content-cms" },
      { title: "Subscription Platform", description: "Paywall systems", href: "/solutions/subscription-platform" },
      { title: "Ad Server", description: "Monetization tools", href: "/solutions/ad-server" },
      { title: "Recommendation AI", description: "Content discovery", href: "/solutions/recommendation-ai" },
      { title: "Social Network", description: "Community platform", href: "/solutions/social-network" },
      { title: "Creator Tools", description: "Studio suite", href: "/solutions/creator-tools" },
      { title: "Ticketing System", description: "Event sales", href: "/solutions/ticketing-system" },
      { title: "Gaming Platform", description: "Multiplayer backend", href: "/solutions/gaming-platform" },
      { title: "NFT Marketplace", description: "Digital collectibles", href: "/solutions/nft-marketplace" },
      { title: "Photo Gallery", description: "Image hosting", href: "/solutions/photo-gallery" },
      { title: "News Portal", description: "Publishing CMS", href: "/solutions/news-portal" },
      { title: "Fan Engagement", description: "Community tools", href: "/solutions/fan-engagement" },
      { title: "Video Editor", description: "Cloud editing", href: "/solutions/video-editor" },
      { title: "Rights Management", description: "Licensing systems", href: "/solutions/rights-management" },
      { title: "Analytics Dashboard", description: "Audience insights", href: "/solutions/analytics-dashboard" },
      { title: "CDN Management", description: "Content delivery", href: "/solutions/cdn-management" },
    ],
  },
  {
    id: "saas",
    name: "SaaS & Enterprise",
    description: "Business software platforms",
    solutions: [
      { title: "CRM Platform", description: "Customer management", href: "/solutions/crm-platform" },
      { title: "Project Management", description: "Team collaboration", href: "/solutions/project-management" },
      { title: "HR Management", description: "People operations", href: "/solutions/hr-management" },
      { title: "Accounting Software", description: "Financial systems", href: "/solutions/accounting-software" },
      { title: "Help Desk", description: "Support ticketing", href: "/solutions/help-desk" },
      { title: "Email Marketing", description: "Campaign automation", href: "/solutions/email-marketing" },
      { title: "Analytics Platform", description: "Business intelligence", href: "/solutions/analytics-platform" },
      { title: "Document Management", description: "File collaboration", href: "/solutions/document-management" },
      { title: "Video Conferencing", description: "Virtual meetings", href: "/solutions/video-conferencing" },
      { title: "Time Tracking", description: "Productivity tools", href: "/solutions/time-tracking" },
      { title: "Inventory System", description: "Stock management", href: "/solutions/inventory-system" },
      { title: "Invoicing", description: "Billing automation", href: "/solutions/invoicing" },
      { title: "Workflow Automation", description: "Process optimization", href: "/solutions/workflow-automation" },
      { title: "Knowledge Base", description: "Documentation hub", href: "/solutions/knowledge-base" },
      { title: "Calendar Booking", description: "Scheduling system", href: "/solutions/calendar-booking" },
      { title: "Form Builder", description: "Data collection", href: "/solutions/form-builder" },
      { title: "Contract Management", description: "Legal workflow", href: "/solutions/contract-management" },
      { title: "Expense Tracking", description: "Spend management", href: "/solutions/expense-tracking" },
      { title: "Survey Platform", description: "Feedback tools", href: "/solutions/survey-platform" },
      { title: "API Gateway", description: "Integration hub", href: "/solutions/api-gateway" },
    ],
  },
];
