// Minimal service index used to toggle visibility of service pages.
// Keep only the service title here so you can comment out entries to hide pages (404).

export const MAIN_SERVICE_TITLES: Record<string, string> = {
  // FinTech
  "payment-gateway": "Payment Gateway",
  "digital-banking": "Digital Banking",
  "blockchain-wallets": "Blockchain Wallets",
  "kyc-automation": "KYC Automation",
  "fraud-detection": "Fraud Detection",
  "lending-platforms": "Lending Platforms",
  "wealth-management": "Wealth Management",
  "insurance-tech": "Insurance Tech",
  "trading-platforms": "Trading Platforms",
  "regtech-compliance": "RegTech Compliance",
//   "p2p-transfers": "P2P Transfers",
//   "neobank-core": "Neobank Core",
//   "credit-scoring": "Credit Scoring",
//   "open-banking-apis": "Open Banking APIs",
//   "pos-systems": "POS Systems",
//   "robo-advisory": "Robo-Advisory",
//   "bill-payment": "Bill Payment",
//   "fx-trading": "FX Trading",
//   "accounting-automation": "Accounting Automation",
//   "tax-compliance": "Tax Compliance",

  // HealthTech
  "telemedicine": "Telemedicine",
//   "ehr-systems": "EHR Systems",
//   "patient-portal": "Patient Portal",
//   "medical-imaging": "Medical Imaging",
//   "lab-management": "Lab Management",
//   "pharmacy-systems": "Pharmacy Systems",
//   "clinical-trials": "Clinical Trials",
//   "health-analytics": "Health Analytics",
//   "remote-monitoring": "Remote Monitoring",
//   "appointment-booking": "Appointment Booking",
//   "medical-billing": "Medical Billing",
//   "drug-discovery": "Drug Discovery",
//   "mental-health-apps": "Mental Health Apps",
//   "care-coordination": "Care Coordination",
//   "medical-devices": "Medical Devices",
//   "health-insurance": "Health Insurance",
//   "genomics-platforms": "Genomics Platforms",
//   "nutrition-tracking": "Nutrition Tracking",
//   "hospital-management": "Hospital Management",
//   "diagnostics-ai": "Diagnostics AI",

  // E-Commerce
  "online-storefront": "Online Storefront",
//   "marketplace-platform": "Marketplace Platform",
//   "product-catalog": "Product Catalog",
//   "shopping-cart": "Shopping Cart",
//   "order-management": "Order Management",
//   "customer-reviews": "Customer Reviews",
//   "recommendation-engine": "Recommendation Engine",
//   "loyalty-programs": "Loyalty Programs",
//   "dynamic-pricing": "Dynamic Pricing",
//   "ar-try-on": "AR Try-On",
//   "subscription-box": "Subscription Box",
//   "live-shopping": "Live Shopping",
//   "social-commerce": "Social Commerce",
//   "warehouse-system": "Warehouse System",
//   "returns-portal": "Returns Portal",
//   "gift-registry": "Gift Registry",
//   "b2b-portal": "B2B Portal",
//   "dropshipping": "Dropshipping",
//   "pos-integration": "POS Integration",
//   "search-filters": "Search & Filters",

  // EdTech
  "lms-platform": "LMS Platform",
//   "virtual-classroom": "Virtual Classroom",
//   "student-portal": "Student Portal",
//   "course-builder": "Course Builder",
//   "assessment-tools": "Assessment Tools",
//   "gradebook": "Gradebook",
//   "video-lectures": "Video Lectures",
//   "interactive-labs": "Interactive Labs",
//   "study-groups": "Study Groups",
//   "certification": "Certification",
//   "tutoring-platform": "Tutoring Platform",
//   "language-learning": "Language Learning",
//   "school-admin": "School Admin",
//   "parent-portal": "Parent Portal",
//   "attendance-tracking": "Attendance Tracking",
//   "library-system": "Library System",
//   "career-services": "Career Services",
//   "alumni-network": "Alumni Network",
//   "admission-portal": "Admission Portal",
//   "learning-analytics": "Learning Analytics",

  // Logistics
  "fleet-management": "Fleet Management",
//   "route-optimization": "Route Optimization",
//   "warehouse-system-logistics": "Warehouse System (Logistics)",
//   "last-mile-delivery": "Last Mile Delivery",
//   "freight-booking": "Freight Booking",
//   "customs-clearance": "Customs Clearance",
//   "track-trace": "Track & Trace",
//   "cold-chain": "Cold Chain",
//   "dock-scheduling": "Dock Scheduling",
//   "returns-logistics": "Returns Logistics",
//   "driver-app": "Driver App",
//   "load-planning": "Load Planning",
//   "customs-broker": "Customs Broker",
//   "cross-docking": "Cross-Docking",
//   "3pl-platform": "3PL Platform",
//   "carrier-portal": "Carrier Portal",
//   "freight-audit": "Freight Audit",
//   "demand-forecasting": "Demand Forecasting",
//   "shipping-labels": "Shipping Labels",
//   "geo-fencing": "Geo-Fencing",

  // Real Estate
  "property-listings": "Property Listings",
//   "virtual-tours": "Virtual Tours",
//   "crm-agents": "CRM for Agents",
//   "booking-system-realestate": "Booking System (Real Estate)",
//   "property-valuation": "Property Valuation",
//   "mortgage-portal": "Mortgage Portal",
//   "lease-management": "Lease Management",
//   "maintenance-requests": "Maintenance Requests",
//   "hoa-portal": "HOA Portal",
//   "rent-collection": "Rent Collection",
//   "smart-home-iot": "Smart Home IoT",
//   "construction-pm": "Construction PM",
//   "bim-platform": "BIM Platform",
//   "bidding-system": "Bidding System",
//   "site-inspection": "Site Inspection",
//   "energy-management": "Energy Management",
//   "coworking-booking": "Co-Working Booking",
//   "property-analytics": "Property Analytics",
//   "document-vault": "Document Vault",
//   "title-search": "Title Search",

  // Automotive
  "fleet-telematics": "Fleet Telematics",
//   "ride-sharing": "Ride Sharing",
//   "car-rental": "Car Rental",
//   "ev-charging": "EV Charging",
//   "auto-insurance": "Auto Insurance",
//   "parts-marketplace": "Parts Marketplace",
//   "service-booking": "Service Booking",
//   "diagnostic-tools": "Diagnostic Tools",
//   "connected-car": "Connected Car",
//   "parking-platform": "Parking Platform",
//   "dealer-crm": "Dealer CRM",
//   "test-drive-booking": "Test Drive Booking",
//   "trade-in-valuation": "Trade-In Valuation",
//   "auto-financing": "Auto Financing",
//   "roadside-assistance": "Roadside Assistance",
//   "vehicle-tracking": "Vehicle Tracking",
//   "carpool-platform": "Carpool Platform",
//   "toll-payment": "Toll Payment",
//   "driver-safety": "Driver Safety",
//   "auction-platform": "Auction Platform",

  // Travel
  "hotel-booking": "Hotel Booking",
//   "flight-search": "Flight Search",
//   "tour-packages": "Tour Packages",
//   "activity-booking": "Activity Booking",
//   "travel-crm": "Travel CRM",
//   "loyalty-programs-travel": "Loyalty Programs (Travel)",
//   "property-management": "Property Management (Hotel)",
//   "channel-manager": "Channel Manager",
//   "revenue-management": "Revenue Management",
//   "guest-portal": "Guest Portal",
//   "concierge-app": "Concierge App",
//   "restaurant-pos": "Restaurant POS",
//   "event-management": "Event Management",
//   "travel-insurance": "Travel Insurance",
//   "visa-services": "Visa Services",
//   "currency-exchange": "Currency Exchange",
//   "cruise-booking": "Cruise Booking",
//   "car-hire": "Car Hire",
//   "travel-guides": "Travel Guides",
//   "group-travel": "Group Travel",

  // Media
  "video-streaming": "Video Streaming",
//   "music-platform": "Music Platform",
//   "podcast-hosting": "Podcast Hosting",
//   "live-broadcasting": "Live Broadcasting",
//   "content-cms": "Content CMS",
//   "subscription-platform": "Subscription Platform",
//   "ad-server": "Ad Server",
//   "recommendation-ai": "Recommendation AI",
//   "social-network": "Social Network",
//   "creator-tools": "Creator Tools",
//   "ticketing-system": "Ticketing System",
//   "gaming-platform": "Gaming Platform",
//   "nft-marketplace": "NFT Marketplace",
//   "photo-gallery": "Photo Gallery",
//   "news-portal": "News Portal",
//   "fan-engagement": "Fan Engagement",
//   "video-editor": "Video Editor",
//   "rights-management": "Rights Management",
//   "analytics-dashboard": "Analytics Dashboard",
//   "cdn-management": "CDN Management",

  // SaaS
  "crm-platform": "CRM Platform",
//   "project-management": "Project Management",
//   "hr-management": "HR Management",
//   "accounting-software": "Accounting Software",
//   "help-desk": "Help Desk",
//   "email-marketing": "Email Marketing",
//   "analytics-platform": "Analytics Platform",
//   "document-management": "Document Management",
//   "video-conferencing": "Video Conferencing",
//   "time-tracking": "Time Tracking",
//   "inventory-system": "Inventory System",
//   "invoicing": "Invoicing",
//   "workflow-automation": "Workflow Automation",
//   "knowledge-base": "Knowledge Base",
//   "calendar-booking": "Calendar Booking",
//   "form-builder": "Form Builder",
//   "contract-management": "Contract Management",
//   "expense-tracking": "Expense Tracking",
//   "survey-platform": "Survey Platform",
//   "api-gateway": "API Gateway",
};

export default MAIN_SERVICE_TITLES;
